<a href="https://colab.research.google.com/github/NITIKA12K/NUMPY-PRACTICE/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#np.array
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
#2D,3D
b=np.array([[1,2,3],[3,4,4]])
print(b)

[[1 2 3]
 [3 4 4]]


In [3]:
c=np.array([[[1,2],[2,3]],[[7,8],[9,0]]])
print(c)

[[[1 2]
  [2 3]]

 [[7 8]
  [9 0]]]


In [4]:
#d.type
np.array([2,3,4],dtype=float)

array([2., 3., 4.])

In [5]:
#np.arange  same as range in python
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [6]:
#with reshape
np.arange(1,13).reshape(3,4)      #only take multiple

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
import numpy as np
#np.ones and np.zeros
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [9]:
np.random.random((3,4))

array([[0.65526655, 0.8055861 , 0.45466329, 0.29983727],
       [0.77457101, 0.2425804 , 0.989788  , 0.28418891],
       [0.01497465, 0.71937243, 0.95003867, 0.00377463]])

In [10]:
#np.linspace   (linearly spaced)
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**ARRAY** **ATTRIBUTES**



In [12]:
a1=np.arange(10,dtype=np.int32)    #32 bits and 4 bytes
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)   #64 bits and 8 bytes
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
a3.ndim

3

In [14]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [16]:
#itemsize   (bytes)
a1.itemsize

4

In [17]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [18]:
#changing datatypes
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**ARRAY OPERATIONS**

In [19]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
a2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
#scalar operations     on one array
#arithmetic
print(a1**2)
#relational
a2==14

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [21]:
#vector operations               on two arrays
#arithmetic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

**ARRAY FUNCTIONS**

In [22]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[95., 29., 80.],
       [14., 73., 32.],
       [33., 42., 91.]])

In [23]:
#max/min/sum/product
#0-->column,1-->row
np.max(a1,axis=0)
np.min(a1)
np.sum(a1)
np.prod(a1)

np.float64(909111364761600.0)

In [24]:
#mean/median/mode/std/var
np.mean(a1,axis=1)

array([68.        , 39.66666667, 55.33333333])

In [25]:
#trigonometric functions
np.sin(a1)

array([[ 0.68326171, -0.66363388, -0.99388865],
       [ 0.99060736, -0.67677196,  0.55142668],
       [ 0.99991186, -0.91652155,  0.10598751]])

In [26]:
#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
print(a2)
print(a3)
np.dot(a2,a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [27]:
#log and exponents
np.exp(a2)
np.log(a2)

/tmp/ipykernel_1071/516898941.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(a2)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [28]:
#round,floor,ceil
print(np.random.random((2,3)))
np.ceil(np.random.random((2,3))*100)

[[0.14594558 0.51454849 0.6777341 ]
 [0.22447885 0.13171946 0.37944154]]


array([[ 6., 99., 69.],
       [70., 99., 38.]])

**INDEXING AND SLICING**

In [39]:
a1=np.arange(10) #1D
a2=np.arange(12).reshape(3,4)   #2D
a3=np.arange(8).reshape(2,2,2) #3D
print(a1)
a1[-1]

[0 1 2 3 4 5 6 7 8 9]


np.int64(9)

In [30]:
print(a2)
a2[2,3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


np.int64(11)

In [31]:
print(a3)
a3[1,0,1]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


np.int64(5)

In [32]:
#slicing
print(a1)
a1[2:5]
a1[2:5:2]

[0 1 2 3 4 5 6 7 8 9]


array([2, 4])

In [33]:
print(a2)
a2[0,:]
a2[:,2]
a2[1:,1:3]
a2[::2,::3]
a2[0::2,1::2]
a2[1,::3]
a2[:2,1:]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[1, 2, 3],
       [5, 6, 7]])

In [34]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [35]:
a3[2]
a3[::2]
a3[0,1,:]
a3[1,0:,1]
a3[2,1:,1:]
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

**ITERATING**

In [41]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [43]:
a2
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [47]:
a3
for i in a3:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [49]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7


**TRANSPOSE AND RAVEL**

In [50]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [52]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [53]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

**STACKING-HORIZONTAL AND VERTICAL**

In [55]:
a4=np.arange(12).reshape(3,4)          #horizontal stacking = same rows
a5=np.arange(12,24).reshape(3,4)
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [56]:
np.vstack((a4,a5))          #vertical stacking = same column

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**SPLITTING-HORIZONTAL AND VERTICAL**

In [57]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [66]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [67]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [69]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [71]:
np.hsplit(a5,2)

[array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]])]